apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert --volumes hostPath
    kompose.version: 1.30.0 (9d8dcb518)
  labels:
    io.kompose.service: prowlarr
  name: prowlarr
  namespace: default
spec:
  type: LoadBalancer
  ports:
    - name: "9696"
      port: 9696
      targetPort: 9696
  selector:
    io.kompose.service: prowlarr
status:
  loadBalancer: {}
