apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
    field.cattle.io/description: Plex Deployment
  creationTimestamp: "2023-02-04T08:01:50Z"
  generation: 1
  labels:
    name: plex
    workload.user.cattle.io/workloadselector: apps.deployment-default-plex-deployment
  name: plex-deployment
  namespace: default
  resourceVersion: "3804"
  uid: 897d0f85-f063-4743-97ae-7cd87f5855d1
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      workload.user.cattle.io/workloadselector: apps.deployment-default-plex-deployment
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      # creationTimestamp: null
      labels:
        name: plex
        workload.user.cattle.io/workloadselector: apps.deployment-default-plex-deployment
    spec:
      affinity: {}
      containers:
      - image: linuxserver/plex
        imagePullPolicy: Always
        name: plex
        ports:
        - containerPort: 32400
          name: 32400tcp32400
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /config
          name: vol-plex-config
        - mountPath: /tv
          name: vol-plex-tv
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - name: vol-plex-config
        persistentVolumeClaim:
          claimName: plex-pvc-config
      - name: vol-plex-tv
        persistentVolumeClaim:
          claimName: plex-pvc-tv
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2023-02-04T08:01:54Z"
    lastUpdateTime: "2023-02-04T08:01:54Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2023-02-04T08:01:50Z"
    lastUpdateTime: "2023-02-04T08:01:54Z"
    message: ReplicaSet "plex-deployment-75bb95b696" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 1
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
