---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: plex-config
  labels:
    name: plex
spec:
  storageClassName: local-path
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  local:
    path: "/mnt/c/Users/dstev/k8s/plex"
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: node
              operator: In
              values:
                -  my-node

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: plex-tv
  labels:
    name: plex
spec:
  storageClassName: local-path
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  local:
    path: "/mnt/c/Users/dstev/TV\ Shows"
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: node
              operator: In
              values:
                -  my-node
