apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert --volumes hostPath
    kompose.version: 1.30.0 (9d8dcb518)
  labels:
    io.kompose.service: ombi
  name: ombi
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: ombi
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert --volumes hostPath
        kompose.version: 1.30.0 (9d8dcb518)
      labels:
        io.kompose.network/kube-network: "true"
        io.kompose.service: ombi
    spec:
      containers:
        - env:
            - name: BASE_URL
              value: /ombi
            - name: PGID
              value: "1000"
            - name: PUID
              value: "1000"
            - name: TZ
              value: Australia/Sydney
          image: lscr.io/linuxserver/ombi@sha256:7e53fa66ac91ccb83b31ce037ae099d1ac2160be19c7f38003e591e4e9f4572c
          name: ombi
          ports:
            - containerPort: 3579
              hostPort: 3579
              protocol: TCP
          resources: {}
          volumeMounts:
            - mountPath: /config
              name: ombi-hostpath0
            - mountPath: /movies
              name: ombi-hostpath1
            - mountPath: /tv
              name: ombi-hostpath2
      restartPolicy: Always
      volumes:
        - hostPath:
            path: /mnt/c/Users/dstev/docker/ombi/config
          name: ombi-hostpath0
        - hostPath:
            path: /mnt/d/Movies
          name: ombi-hostpath1
        - hostPath:
            path: /mnt/d/TV Shows
          name: ombi-hostpath2
status: {}
