apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert --volumes hostPath
    kompose.version: 1.30.0 (9d8dcb518)
  labels:
    io.kompose.service: ombi
  name: ombi
  namespace: default
spec:
  type: NodePort
  ports:
    - name: "3579"
      port: 3579
      targetPort: 3579
  selector:
    io.kompose.service: ombi
status:
  loadBalancer: {}
