apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert --volumes hostPath
    kompose.version: 1.30.0 (9d8dcb518)
  labels:
    io.kompose.service: portainer
  name: portainer
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: portainer
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert --volumes hostPath
        kompose.version: 1.30.0 (9d8dcb518)
      labels:
        io.kompose.network/kube-default: "true"
        io.kompose.service: portainer
    spec:
      containers:
        - args:
            - -H
            - unix:///var/run/docker.sock
          image: portainer/portainer-ce@sha256:77cfdbc5289e91bbb13b411ca72d433d4b4b99f3c51ddd1869e7f2952faa0ee2
          name: portainer
          ports:
            - containerPort: 9000
              hostPort: 9000
              protocol: TCP
            - containerPort: 8000
              hostPort: 8000
              protocol: TCP
          resources: {}
          volumeMounts:
            - mountPath: /var/run/docker.sock
              name: portainer-hostpath0
            - mountPath: /data
              name: portainer-hostpath1
      restartPolicy: Always
      volumes:
        - hostPath:
            path: /var/run/docker.sock
          name: portainer-hostpath0
        - hostPath:
            path: /mnt/c/Users/dstev/docker/portainer/portainer_data
          name: portainer-hostpath1
status: {}
