apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert --volumes hostPath
    kompose.version: 1.30.0 (9d8dcb518)
  labels:
    io.kompose.service: prowlarr
  name: prowlarr
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: prowlarr
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert --volumes hostPath
        kompose.version: 1.30.0 (9d8dcb518)
      labels:
        io.kompose.network/kube-network: "true"
        io.kompose.service: prowlarr
    spec:
      restartPolicy: Always
      containers:
        - env:
            - name: PGID
              value: "1000"
            - name: PUID
              value: "1000"
            - name: TZ
              value: Etc/UTC
          image: lscr.io/linuxserver/prowlarr@sha256:a2d1b666ca37f069854c2b526b8681b7867f954384d250b71493f0396c143f19
          name: prowlarr
          ports:
            - containerPort: 9696
              hostPort: 9696
              protocol: TCP
          resources: {}
          volumeMounts:
            - mountPath: /config
              name: prowlarr-hostpath0
      volumes:
        - hostPath:
            path: /mnt/d/docker/prowlarr/config
          name: prowlarr-hostpath0
status: {}
