apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert --volumes hostPath
    kompose.version: 1.30.0 (9d8dcb518)
  labels:
    io.kompose.service: radarr
  name: radarr
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: radarr
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert --volumes hostPath
        kompose.version: 1.30.0 (9d8dcb518)
      labels:
        io.kompose.network/kube-network: "true"
        io.kompose.service: radarr
    spec:
      containers:
        - env:
            - name: PGID
              value: "1000"
            - name: PUID
              value: "1000"
            - name: TZ
              value: Australia/Sydney
            - name: UMASK
              value: "022"
          image: ghcr.io/linuxserver/radarr@sha256:3a0932a2fae8a529fe06ac0fb9d1f85c81e01b1a03ef6c7e119120410cea90e3
          name: radarr
          ports:
            - containerPort: 7878
              hostPort: 7878
              protocol: TCP
          resources: {}
          volumeMounts:
            - mountPath: /config
              name: radarr-hostpath0
            - mountPath: /movies
              name: radarr-hostpath1
            - mountPath: /downloads
              name: radarr-hostpath2
      restartPolicy: Always
      volumes:
        - hostPath:
            path: /mnt/c/Users/dstev/docker/radarr/config
          name: radarr-hostpath0
        - hostPath:
            path: /mnt/d/Movies
          name: radarr-hostpath1
        - hostPath:
            path: /mnt/d/Downloads
          name: radarr-hostpath2
status: {}
