apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: sonarr
  name: sonarr
  namespace: default
spec:
  type: ClusterIP
  ports:
    - name: "8989"
      port: 8989
      targetPort: 8989
  selector:
    io.kompose.service: sonarr