apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert --volumes hostPath
    kompose.version: 1.30.0 (9d8dcb518)
  labels:
    io.kompose.service: transmission
  name: transmission
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: transmission
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert --volumes hostPath
        kompose.version: 1.30.0 (9d8dcb518)
      labels:
        io.kompose.network/kube-network: "true"
        io.kompose.service: transmission
    spec:
      containers:
        - env:
            - name: PGID
              value: "1000"
            - name: PUID
              value: "1000"
            - name: TZ
              value: Etc/UTC
          image: lscr.io/linuxserver/transmission@sha256:01960e99150a3f0faf8f0169f35672c0fb9f8bc711c7cbf7086c63576f5f7bd1
          name: transmission
          ports:
            - containerPort: 9091
              hostPort: 9091
              protocol: TCP
            - containerPort: 51413
              hostPort: 51413
              protocol: TCP
          resources: {}
          volumeMounts:
            - mountPath: /config
              name: transmission-hostpath0
            - mountPath: /downloads
              name: transmission-hostpath1
            - mountPath: /watch
              name: transmission-hostpath2
      restartPolicy: Always
      volumes:
        - hostPath:
            path: /mnt/d/docker/transmission/config
          name: transmission-hostpath0
        - hostPath:
            path: /mnt/d/Downloads
          name: transmission-hostpath1
        - hostPath:
            path: /mnt/d/docker/transmission/watch
          name: transmission-hostpath2
status: {}
